name: Deploy to Amazon App Runner

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-west-2 # London
  ECR_REPOSITORY: alzafar-backend
  SERVICE_NAME: alzafar-backend-service

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to Amazon App Runner
      uses: awslabs/amazon-app-runner-deploy@main
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE_ARN }}
        region: ${{ env.AWS_REGION }}
        cpu: 1
        memory: 2
        wait-for-service-stability-seconds: 600
